### ISSUE TITLE
UnicodeDecodeError when trying to read and save hostkey

### ISSUE THREAD

**Issue by mashirozx** [fffonion/cloudflare-partner-cli#1]
```
C:\WorkDirectory\GitHub\cloudflare-partner-cli>python ./cloudflare-partner-cli.py
请输入 Cloudflare hostkey (https://partners.cloudflare.com/api-management)> 3cad5381326ab4c***********
Traceback (most recent call last):
  File "./cloudflare-partner-cli.py", line 351, in <module>
    check_hostkey()
  File "./cloudflare-partner-cli.py", line 324, in check_hostkey
    script = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 905: illegal multibyte sequence
```

What should I do to solve this? Thanks :)

**Comment by mashirozx** [comment]
Problem solved.
In line 323 should be this:
```python
with open(__file__,encoding='UTF-8') as f:
```

**Comment by fffonion** [comment]
Thanks for reporting this.

I think the better solution here is to open `__file__` as binary file, so we won't need to touch codec stuff.

**Comment by fffonion** [comment]
This has been fixed : )

**Comment by mashirozx** [comment]
Thanks:smile:
