### ISSUE TITLE
申請 SSL 失敗

### ISSUE THREAD

**Issue by ghost** [fffonion/cloudflare-partner-cli#2]
報錯如下:
```Traceback (most recent call last):
  File "./cloudflare-partner-cli.py", line 375, in <module>
    getattr(cf, act)(arg)
  File "./cloudflare-partner-cli.py", line 209, in ssl_verfication
    r = self._userapi("/zones/%s/ssl/verification?retry=true" % zone_id)
  File "./cloudflare-partner-cli.py", line 172, in _userapi
    r = opener.open(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request```

**Comment by safly** [comment]
Traceback (most recent call last):
  File "cloudflare-partner-cli.py", line 375, in <module>
    getattr(cf, act)(arg)
  File "cloudflare-partner-cli.py", line 204, in ssl_verfication
    r = self._userapi("/zones?name=%s&match=all" % arg['zone'])
  File "cloudflare-partner-cli.py", line 172, in _userapi
    r = opener.open(req).read()
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
