### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by safly** [fffonion/cloudflare-partner-cli#3]
Python 2.7.9，Linux example01 4.15.17-3-pve #1 SMP PVE 4.15.17-14 (Wed, 27 Jun 2018 17:18:05 +0200) x86_64 GNU/Linux

root@example01:/www/cloudflare# sudo python ./cloudflare-partner-cli.py 

Traceback (most recent call last):
  File "./cloudflare-partner-cli.py", line 366, in <module>
    check_hostkey()
  File "./cloudflare-partner-cli.py", line 334, in check_hostkey
    HOSTKEY = raw_input(i18n("Please enter your Cloudflare partner hostkey (https://partners.cloudflare.com/api-management)> ")).strip()
  File "./cloudflare-partner-cli.py", line 92, in i18n
    if LOCALE[1].lower() == "cp936" and not PY3K: # windows with simplified Chinese locale
AttributeError: 'NoneType' object has no attribute 'lower'

不是很懂python，麻烦大佬了

**Comment by safly** [comment]
python 2.7 3.4 3.6都不行，3.7运行起来了

**Comment by safly** [comment]
选择所需的操作，输入数字：
1. 添加/修改DNS记录
2. 删除DNS记录
3. 重新生成host key
4. 开通SSL
5. 删除接入的域名
6. 显示所有接入的域名
7. 显示DNS记录
8. 接入域名
9. 退出当前帐号
> 4
根域名 > xxx.xxx
Traceback (most recent call last):
  File "cloudflare-partner-cli.py", line 375, in <module>
    getattr(cf, act)(arg)
  File "cloudflare-partner-cli.py", line 204, in ssl_verfication
    r = self._userapi("/zones?name=%s&match=all" % arg['zone'])
  File "cloudflare-partner-cli.py", line 172, in _userapi
    r = opener.open(req).read()
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1270, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.7/http/client.py", line 1206, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

**Comment by safly** [comment]
Traceback (most recent call last):
  File "cloudflare-partner-cli.py", line 375, in <module>
    getattr(cf, act)(arg)
  File "cloudflare-partner-cli.py", line 204, in ssl_verfication
    r = self._userapi("/zones?name=%s&match=all" % arg['zone'])
  File "cloudflare-partner-cli.py", line 172, in _userapi
    r = opener.open(req).read()
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
